name: PR

on:
  pull_request:
    branches: [ main ]

jobs:
  gomod:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.24', '1.23']
    name: Go ${{ matrix.go }}.x PR Validate (Modules)
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
      - name: Version
        run: go version
      - name: Build and Validate
        run: |
          go vet .
          go test .
          go test -cover -race -cpu 1,2,4 .
          go build .

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v1.64.8
          only-new-issues: true
